spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.31.5:3307/weizi_film_television?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  # 配置Redis
  data:
    redis:
      # 地址
      host: 192.168.31.5
      # 数据库索引
      database: 0
      # 端口号
      port: 6379
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
# 自定义上传文件大小
file-upload:
  avatar:
    image-types: image/jpeg, image/png
    image-base64-types:
      jpg: data:image/jpg;base64,
      jpeg: data:image/jpeg;base64,
      png: data:image/png;base64,
    max-size: 5MB
server:
  port: 9090
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
item:
  avatar-path: "D:/XiaoBai/admin/avatar/"
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG