spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/weizi_film_television?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  # 配置Redis
  data:
    redis:
      # 地址
      host: 127.0.0.1
      # 数据库索引
      database: 0
      # 端口号
      port: 6379
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  servlet:
    multipart:
      enabled: true
      # 不限制文件大小
      max-file-size: -1
      # 不限制请求体大小
      max-request-size: -1
      # 临时IO目录
      # location: "${java.io.tmpdir}"
      # 不延迟解析
      resolve-lazily: false
      # 超过1Mb，就IO到临时目录
      # file-size-threshold: 5MB
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:D:\\XiaoBai\\admin\\video\\sliceMovie
# 自定义上传文件大小
file-upload:
  avatar:
    image-types: image/jpeg, image/png
    image-base64-types:
      jpg: data:image/jpg;base64,
      jpeg: data:image/jpeg;base64,
      png: data:image/png;base64,
    max-size: 5MB
server:
  port: 9090
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
item:
  static-path: "src/main/resources/static" # 存储头像的静态目录下的文件夹（用于上传的时候用的）
  avatar-path: "D:/XiaoBai/admin/avatar/" # 存储头像的路径写死
  poster-path: "/images/poster/" # 存储海报的静态目录下的文件夹
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
# 配置超级管理员的id
superadmin:
  id: 1
app:
  # 存储转码视频的文件夹
  video-folder: "D:/XiaoBai/admin/ffmpegVideo/"
  # 允许上传的视频格式（暂时先这两个格式）
  allowed-file-types: mp4,mkv
# 视频文件路径
video:
  temp-folder: "D:/XiaoBai/admin/video/temp/"
  slice-movie-folder: "D:/XiaoBai/admin/video/sliceMovie/"
  movie-folder: "D:/XiaoBai/admin/video/movie/"
ffmpeg:
  ffmpeg-exe: "D:/javaTool/ffmpeg-6.1.1-full_build/bin/ffmpeg.exe"
  ffprobe-exe: "D:/javaTool/ffmpeg-6.1.1-full_build/bin/ffprobe.exe"
  movie-slice-duration: 1 # 切片时长（s）
# 自定义minio 参数配置
minio:
  endpoint: http://localhost:9000 # MinIO服务所在地址和端口号
  access-key: ciKCR3sS0JQIsANqShAq # 访问的key
  secret-key: KoXWbJ0oQ8pzvvSNMy29xRiWXFv99cWmYLCGR3Yd # 访问的秘钥
  bucket-name: formal-file
  bucket-name-slice: slice-file
  bucket-name-slice-moive: slice-movie-file
sequential-file-processor:
  max-threads: 1 # ffmpeg文件切片最大线程数

